language: python
python:
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y par2
install:
    - pip install -U setuptools
    - python bootstrap.py
    - ./bin/buildout
before_script:
    - ./bin/flake8 easy_extract
script:
    - ./bin/cover
after_success:
    - ./bin/coveralls
notifications:
    irc:
        - "irc.freenode.org#easy-extract"
